name: Install dependencies
description: Install dependencies
inputs:
  terraform-version:
    description: 'Terraform version'
    required: true
    default: ""

runs:
  using: composite
  steps:

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      if: ${{ inputs.terraform-version != '' }}
      with:
        terraform_version: ${{ inputs.terraform-version }}
