name: Terraform Plan
description: Generate Terraform Plan
inputs:
  working-directory:
    description: 'Working directory'
    required: true
  plan-artifact-name:
    description: 'Artifact name of plan'
    required: false
    default: ""
  plan-artifact-file:
    description: 'Artifact file of plan'
    required: false
    default: ""

runs:
  using: composite
  steps:

    - name: Initialize terraform
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: terraform init -backend-config=../backend-config.json -reconfigure -upgrade

    - name: Validate terraform configuration
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: terraform validate

    - name: Generate terraform plan
      if: ${{ inputs.plan-artifact-name != '' }}
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: terraform plan -out=${{ inputs.plan-artifact-file }}

    - name: Save terraform plan as artifact
      if: ${{ inputs.plan-artifact-name != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.plan-artifact-name }}
        path: ${{ inputs.working-directory }}/${{ inputs.plan-artifact-file }}
