---
name: Validate Repositories

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

env:
  TF_VERSION: "1.10.2"

jobs:
  verify-repositories:
    name: Check terraform code
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get common secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
              ${{ secrets.AWS_ACCESS_KEY_ID }} > AWS_ACCESS_KEY_ID
              ${{ secrets.AWS_SECRET_ACCESS_KEY }} > AWS_SECRET_ACCESS_KEY
              ${{ secrets.TF_BUCKET }} > S3_BUCKET
              ${{ secrets.TF_REGION }} > S3_REGION
              ${{ secrets.TF_ENDPOINT }} > S3_ENDPOINT
              ${{ secrets.TOKEN_GITHUB }} > GITHUB_TOKEN
              ${{ secrets.TOKEN_GITLAB }} > GITLAB_TOKEN

      - name: Initialize job
        uses: ./.github/actions/initialize-job
        with:
          terraform-version: ${{ env.TF_VERSION }}

      - name: Validate terraform
        uses: ./.github/actions/terraform-plan
        with:
          working-directory: src/repositories
